/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jbjQHDjB2pK
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { Archivo } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { useMediaQuery } from "react-responsive";
import { ProductListerProps } from "@/settings/components/ProductLister";

export function ProductList(props: ProductListerProps) {
  const isMobile = useMediaQuery({
    query: "(max-width: 1224px)",
  });
  const products = props.products;

  return (
    <>
      <header className="flex items-center justify-between px-4 py-2 bg-gray-800 text-white">
        <h1 className="text-xl font-bold">{props.title}</h1>
      </header>
      <div className="container mx-auto grid grid-cols-1 md:grid-cols-4 lg:grid-cols-5 gap-4 p-4">
        <div className={` md:col-span-1 ` + (isMobile ? "hidden" : "block")}>
          <div className="mb-4">
            <Input
              className="w-full rounded-md border border-gray-200 border-gray-300 px-4 py-2 text-gray-900 placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:placeholder:text-gray-400 dark:focus:ring-offset-gray-700 dark:border-gray-800"
              placeholder="Search products..."
              type="search"
            />
          </div>
          <div className="mb-4">
            <h3 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">
              Categories
            </h3>
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <Checkbox
                  className="text-indigo-600 focus:ring-indigo-600 dark:ring-offset-gray-700 dark:bg-gray-600 dark:border-gray-500"
                  id="category-electronics"
                />
                <Label
                  className="text-sm text-gray-900 dark:text-white"
                  htmlFor="category-electronics"
                >
                  Electronics
                </Label>
              </div>
              <div className="flex items-center gap-2">
                <Checkbox
                  className="text-indigo-600 focus:ring-indigo-600 dark:ring-offset-gray-700 dark:bg-gray-600 dark:border-gray-500"
                  id="category-clothing"
                />
                <Label
                  className="text-sm text-gray-900 dark:text-white"
                  htmlFor="category-clothing"
                >
                  Clothing
                </Label>
              </div>
              <div className="flex items-center gap-2">
                <Checkbox
                  className="text-indigo-600 focus:ring-indigo-600 dark:ring-offset-gray-700 dark:bg-gray-600 dark:border-gray-500"
                  id="category-books"
                />
                <Label
                  className="text-sm text-gray-900 dark:text-white"
                  htmlFor="category-books"
                >
                  Books
                </Label>
              </div>
              <div className="flex items-center gap-2">
                <Checkbox
                  className="text-indigo-600 focus:ring-indigo-600 dark:ring-offset-gray-700 dark:bg-gray-600 dark:border-gray-500"
                  id="category-home"
                />
                <Label
                  className="text-sm text-gray-900 dark:text-white"
                  htmlFor="category-home"
                >
                  Home & Garden
                </Label>
              </div>
            </div>
          </div>
          <div className="mb-4">
            <h3 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">
              Price Range
            </h3>
            <div className="flex items-center gap-2">
              <Input
                className="w-24 rounded-md border border-gray-200 border-gray-300 px-4 py-2 text-gray-900 placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:placeholder:text-gray-400 dark:focus:ring-offset-gray-700 dark:border-gray-800"
                placeholder="Min"
                type="number"
              />
              <span className="text-gray-500 dark:text-gray-400">-</span>
              <Input
                className="w-24 rounded-md border border-gray-200 border-gray-300 px-4 py-2 text-gray-900 placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:placeholder:text-gray-400 dark:focus:ring-offset-gray-700 dark:border-gray-800"
                placeholder="Max"
                type="number"
              />
            </div>
          </div>
          <div className="mb-4">
            <h3 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">
              Rating
            </h3>
            <div className="flex items-center gap-2">
              <div className="flex items-center gap-1">
                <StarIcon className="w-4 h-4 fill-yellow-400 dark:fill-yellow-300" />
                <StarIcon className="w-4 h-4 fill-yellow-400 dark:fill-yellow-300" />
                <StarIcon className="w-4 h-4 fill-yellow-400 dark:fill-yellow-300" />
                <StarIcon className="w-4 h-4 fill-yellow-400 dark:fill-yellow-300" />
                <StarIcon className="w-4 h-4 fill-gray-300 dark:fill-gray-500" />
              </div>
              <span className="text-gray-500 text-sm dark:text-gray-400">
                & Up
              </span>
            </div>
          </div>
        </div>
        <div
          className={
            "md:col-span-3 lg:col-span-4" + (!isMobile ? "hidden" : "block")
          }
        >
          {isMobile && (
            <div className={"mb-4" + (!isMobile ? "hidden" : "block")}>
              <Input
                className="w-full rounded-md border border-gray-200 border-gray-300 px-4 py-2 text-gray-900 placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:placeholder:text-gray-400 dark:focus:ring-offset-gray-700 dark:border-gray-800"
                placeholder="Search products..."
                type="search"
              />
            </div>
          )}
          <div className="md:hidden mb-4">
            <h3 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">
              Categories
            </h3>
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2">
                <Checkbox
                  className="text-indigo-600 focus:ring-indigo-600 dark:ring-offset-gray-700 dark:bg-gray-600 dark:border-gray-500"
                  id="category-electronics-mobile"
                />
                <Label
                  className="text-sm text-gray-900 dark:text-white"
                  htmlFor="category-electronics-mobile"
                >
                  Electronics
                </Label>
              </div>
              <div className="flex items-center gap-2">
                <Checkbox
                  className="text-indigo-600 focus:ring-indigo-600 dark:ring-offset-gray-700 dark:bg-gray-600 dark:border-gray-500"
                  id="category-clothing-mobile"
                />
                <Label
                  className="text-sm text-gray-900 dark:text-white"
                  htmlFor="category-clothing-mobile"
                >
                  Clothing
                </Label>
              </div>
              <div className="flex items-center gap-2">
                <Checkbox
                  className="text-indigo-600 focus:ring-indigo-600 dark:ring-offset-gray-700 dark:bg-gray-600 dark:border-gray-500"
                  id="category-books-mobile"
                />
                <Label
                  className="text-sm text-gray-900 dark:text-white"
                  htmlFor="category-books-mobile"
                >
                  Books
                </Label>
              </div>
              <div className="flex items-center gap-2">
                <Checkbox
                  className="text-indigo-600 focus:ring-indigo-600 dark:ring-offset-gray-700 dark:bg-gray-600 dark:border-gray-500"
                  id="category-home-mobile"
                />
                <Label
                  className="text-sm text-gray-900 dark:text-white"
                  htmlFor="category-home-mobile"
                >
                  Home & Garden
                </Label>
              </div>
            </div>
          </div>
          <div className="md:hidden mb-4">
            <h3 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">
              Price Range
            </h3>
            <div className="flex items-center gap-2">
              <Input
                className="w-24 rounded-md border border-gray-200 border-gray-300 px-4 py-2 text-gray-900 placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:placeholder:text-gray-400 dark:focus:ring-offset-gray-700 dark:border-gray-800"
                placeholder="Min"
                type="number"
              />
              <span className="text-gray-500 dark:text-gray-400">-</span>
              <Input
                className="w-24 rounded-md border border-gray-200 border-gray-300 px-4 py-2 text-gray-900 placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:placeholder:text-gray-400 dark:focus:ring-offset-gray-700 dark:border-gray-800"
                placeholder="Max"
                type="number"
              />
            </div>
          </div>
          <div className="md:hidden mb-4">
            <h3 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">
              Rating
            </h3>
            <div className="flex items-center gap-2">
              <div className="flex items-center gap-1">
                <StarIcon className="w-4 h-4 fill-yellow-400 dark:fill-yellow-300" />
                <StarIcon className="w-4 h-4 fill-yellow-400 dark:fill-yellow-300" />
                <StarIcon className="w-4 h-4 fill-yellow-400 dark:fill-yellow-300" />
                <StarIcon className="w-4 h-4 fill-yellow-400 dark:fill-yellow-300" />
                <StarIcon className="w-4 h-4 fill-gray-300 dark:fill-gray-500" />
              </div>
              <span className="text-gray-500 text-sm dark:text-gray-400">
                & Up
              </span>
            </div>
          </div>
          <div className="mb-4">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white">
              Products
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {products.map((product, key) => (
              <div
                key={key}
                className="bg-white rounded-lg shadow-md overflow-hidden group relative dark:bg-gray-800"
              >
                <Link className="absolute inset-0 z-10" href="#">
                  <span className="sr-only">View product</span>
                </Link>
                <div className="aspect-square overflow-hidden">
                  <img
                    alt="Product Image"
                    className="object-cover w-full h-full group-hover:scale-105 transition-transform duration-300"
                    height={500}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "500/500",
                      objectFit: "cover",
                    }}
                    width={500}
                  />
                </div>
                <div className="p-4">
                  <h3 className="text-lg font-semibold mb-1 text-gray-900 dark:text-white">
                    {product.product_name}
                  </h3>
                  <p className="text-gray-500 mb-2 dark:text-gray-400">
                    Category Name
                  </p>
                  <div className="flex items-center justify-between">
                    <span className="text-xl font-bold text-gray-900 dark:text-white">
                      $99.99
                    </span>
                    <Button
                      className="bg-indigo-600 hover:bg-indigo-700 text-white focus:outline-none focus:ring-2 focus:ring-indigo-600 focus:ring-offset-2 dark:focus:ring-offset-gray-700"
                      size="sm"
                    >
                      Add to Cart
                    </Button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  );
}

function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}
